project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - text: Home
        menu:
          - href: index.qmd
            text: Congestion Graph
          - href: population-plot-census.qmd
            text: Population graph for comparison and connections
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
