project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Graphs and Tables
        menu:
          - href: congestion-plot.qmd
            text: Congestion Graph
          - href: population-plot-census.qmd
            text: Population Graph
          - href: data-table.qmd
            text: Table
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
