---
title: "January 2024 Trafic Congestion Factor in Massachusetts"
author: "Ayush Chandra"
execute:
    echo: false
    message: false
    warning: false
---

Have you ever been tired or fed up with traffic congestion delays and are just dying to get out? I've been exploring the different traffic congestion levels all around Massachusetts in January of 2024, using a data set from [Mass.gov](https://www.mass.gov/traffic-volume-and-classification-in-massachusetts?_gl=1*x4zy9j*_ga*MjM0Mjk4NzExLjE3NTE1NzY1ODU.*_ga_MCLPEGW7WM*czE3NTE1NzcxMTgkbzEkZzEkdDE3NTE1NzcyMjEkajYwJGwwJGgw). Today, I have compiled the data into an interactive graph that lets you see the traffic congestion levels in most of the cities within MA. I also made another graph about the Jan 2024 Massachusetts census data to compare the congestion levels to the population. I have found that the highest levels of congestion are near Cape Cod, while the lowest congestion levels are closer to the middle and eastern sides of the state. Feel free to look around and enjoy!


```{r}
library(dplyr)
library(leaflet)
library(sf)
library(tigris)
library(readr)
library(tidyverse)
library(tibble)
library(dplyr)
library(leaflet)
library(sf)
library(tigris)

library(tibble)

congestion_data <- tribble(
  ~City,                ~County,     ~Region_Group,     ~JAN_2024_Factor,
  "Abington", "Plymouth", "U1-Southeast", 1.14,
  "Acton", "Middlesex", "U1-West", 1.10,
  "Acushnet Center", "Bristol", "U1-Southeast", 1.14,
  "Adams", "Berkshire", "R1", 1.17,
  "Agawam Town", "Hampden", "U1-West", 1.10,
  "Alford", "Berkshire", "R1", 1.17,
  "Amesbury", "Essex", "U1-Essex", 1.13,
  "Amherst Town", "Hampshire", "U1-West", 1.10,
  "Andover", "Essex", "U1-Essex", 1.13,
  "Arlington", "Middlesex", "U1-Boston", 1.07,
  "Ashburnham", "Worcester", "U1-Worcester", 1.08,
  "South Ashburnham", "Worcester", "U1-Worcester", 1.08,
  "Ashby", "Middlesex", "U1-West", 1.10,
  "Ashfield", "Franklin", "R1", 1.17,
  "Ashland", "Middlesex", "U1-West", 1.10,
  "Athol", "Worcester", "U1-West", 1.10,
  "Attleboro", "Bristol", "U1-Southeast", 1.14,
  "North Attleboro Town", "Bristol", "U1-Southeast", 1.14,
  "Auburn", "Worcester", "U1-Worcester", 1.08,
  "Avon", "Norfolk", "U1-Boston", 1.07,
  "Ayer", "Middlesex", "U1-West", 1.10,
  "Barnstable Town", "Barnstable", "Rec - East", 1.21,
  "Barre", "Worcester", "U1-West", 1.10,
  "Becket", "Berkshire", "R1", 1.17,
  "Bedford", "Middlesex", "U1-Boston", 1.07,
  "Belchertown", "Hampshire", "U1-West", 1.10,
  "Bellingham", "Norfolk", "U1-Southeast", 1.14,
  "Belmont", "Middlesex", "U1-Boston", 1.07,
  "Berkley", "Bristol", "U1-Southeast", 1.14,
  "Berlin", "Worcester", "U1-West", 1.10,
  "Bernardston", "Franklin", "R1", 1.17,
  "Beverly", "Essex", "U1-Essex", 1.13,
  "Billerica", "Middlesex", "U1-Boston", 1.07,
  "Blackstone", "Worcester", "U1-Southeast", 1.14,
  "Blandford", "Hampden", "U1-West", 1.10,
  "Bolton", "Worcester", "U1-West", 1.10,
  "Boston", "Suffolk", "U1-Boston", 1.07,
  "Bourne", "Barnstable", "Rec - East", 1.21,
  "Boxborough", "Middlesex", "U1-West", 1.10,
  "Boxford", "Essex", "U1-Essex", 1.13,
  "Boylston", "Worcester", "U1-Worcester", 1.08,
  "Braintree Town", "Norfolk", "U1-Boston", 1.07,
  "Brewster", "Barnstable", "Rec - East", 1.21,
  "Bridgewater Town", "Plymouth", "U1-Southeast", 1.14,
  "Brimfield", "Hampden", "U1-West", 1.10,
  "Brockton", "Plymouth", "U1-Southeast", 1.14,
  "Brookfield", "Worcester", "U1-West", 1.10,
  "Brookline", "Norfolk", "U1-Boston", 1.07,
  "Buckland", "Franklin", "R1", 1.17,
  "Burlington", "Middlesex", "U1-Boston", 1.07,
  "Cambridge", "Middlesex", "U1-Boston", 1.07,
  "Canton", "Norfolk", "U1-Boston", 1.07,
  "Carlisle", "Middlesex", "U1-Boston", 1.07,
  "Carver", "Plymouth", "U1-Southeast", 1.14,
  "Charlemont", "Franklin", "R1", 1.17,
  "Charlton", "Worcester", "U1-Worcester", 1.08,
  "Chatham", "Barnstable", "Rec - East", 1.21,
  "West Chatham", "Barnstable", "Rec - East", 1.21,
  "Chelmsford", "Middlesex", "U1-Boston", 1.07,
  "Chelsea", "Suffolk", "U1-Boston", 1.07,
  "Cheshire", "Berkshire", "R1", 1.17,
  "Chester", "Hampden", "U1-West", 1.10,
  "Chesterfield", "Hampshire", "U1-West", 1.10,
  "Chicopee", "Hampden", "U1-West", 1.10,
  "Chilmark", "Dukes", "Rec - Islands", 1.23,
  "Clarksburg", "Berkshire", "R1", 1.17,
  "Clinton", "Worcester", "U1-Worcester", 1.08,
  "Cohasset", "Norfolk", "U1-Boston", 1.07,
  "Colrain", "Franklin", "R1", 1.17,
  "Concord", "Middlesex", "U1-Boston", 1.07,
  "West Concord", "Middlesex", "U1-Boston", 1.07,
  "Conway", "Franklin", "R1", 1.17,
  "Cummington", "Hampshire", "R1", 1.17,
  "Dalton", "Berkshire", "R1", 1.17,
  "Danvers", "Essex", "U1-Essex", 1.13,
  "Dartmouth", "Bristol", "U1-Southeast", 1.14,
  "Dedham", "Norfolk", "U1-Boston", 1.07,
  "Deerfield", "Franklin", "U1-West", 1.10,
  "South Deerfield", "Franklin", "U1-West", 1.10,
  "Dennis Port", "Barnstable", "Rec - East", 1.21,
  "Dennis", "Barnstable", "Rec - East", 1.21,
  "South Dennis", "Barnstable", "Rec - East", 1.21,
  "East Dennis", "Barnstable", "Rec - East", 1.21,
  "West Dennis", "Barnstable", "Rec - East", 1.21,
  "Dighton", "Bristol", "U1-Southeast", 1.14,
  "Douglas", "Worcester", "U1-Worcester", 1.08,
  "Dover", "Norfolk", "U1-Boston", 1.07,
  "Dracut", "Middlesex", "U1-Boston", 1.07,
  "Dudley", "Worcester", "U1-Worcester", 1.08,
  "Dunstable", "Middlesex", "U1-Boston", 1.07,
  "Duxbury", "Plymouth", "U1-Southeast", 1.14,
  "South Duxbury", "Plymouth", "U1-Southeast", 1.14,
  "East Bridgewater", "Plymouth", "U1-Southeast", 1.14,
  "East Brookfield", "Worcester", "U1-Worcester", 1.08,
  "East Longmeadow", "Hampden", "U1-West", 1.10,
  "Eastham", "Barnstable", "Rec - East", 1.21,
  "North Eastham", "Barnstable", "Rec - East", 1.21,
  "Easthampton", "Hampshire", "U1-West", 1.10,
  "Easton", "Bristol", "U1-Southeast", 1.14,
  "Edgartown", "Dukes", "Rec - Islands", 1.23,
  "Egremont", "Berkshire", "R1", 1.17,
  "Erving", "Franklin", "U1-West", 1.10,
  "Essex", "Essex", "U1-Essex", 1.13,
  "Everett", "Middlesex", "U1-Boston", 1.07,
  "Fairhaven", "Bristol", "U1-Southeast", 1.14,
  "Fall River", "Bristol", "U1-Southeast", 1.14,
  "Falmouth", "Barnstable", "Rec - East", 1.21,
  "North Falmouth", "Barnstable", "Rec - East", 1.21,
  "West Falmouth", "Barnstable", "Rec - East", 1.21,
  "East Falmouth", "Barnstable", "Rec - East", 1.21,
  "Fitchburg", "Worcester", "U1-Worcester", 1.08,
  "Florida", "Berkshire", "R1", 1.17,
  "Foxborough", "Norfolk", "U1-Southeast", 1.14,
  "Framingham", "Middlesex", "U1-Boston", 1.07,
  "Franklin Town", "Norfolk", "U1-Southeast", 1.14,
  "Freetown", "Bristol", "U1-Southeast", 1.14,
  "Gardner", "Worcester", "U1-Worcester", 1.08,
  "Aquinnah", "Dukes", "Rec - Islands", 1.23,
  "Georgetown", "Essex", "U1-Essex", 1.13,
  "Gill", "Franklin", "U1-West", 1.10,
  "Gloucester", "Essex", "U1-Essex", 1.13,
  "Goshen", "Hampshire", "U1-West", 1.10,
  "Gosnold", "Dukes", "Rec - Islands", 1.23,
  "Grafton", "Worcester", "U1-Worcester", 1.08,
  "Granby", "Hampshire", "U1-West", 1.10,
  "Granville", "Hampden", "U1-West", 1.10,
  "Great Barrington", "Berkshire", "R1", 1.17,
  "Greenfield", "Franklin", "U1-West", 1.10,
  "Groton", "Middlesex", "U1-Boston", 1.07,
  "Groveland", "Essex", "U1-Essex", 1.13,
  "Hadley", "Hampshire", "U1-West", 1.10,
  "Halifax", "Plymouth", "U1-Southeast", 1.14,
  "Hamilton", "Essex", "U1-Essex", 1.13,
  "Hampden", "Hampden", "U1-West", 1.10,
  "Hancock", "Berkshire", "R1", 1.17,
  "Hanover", "Plymouth", "U1-Southeast", 1.14,
  "Hanson", "Plymouth", "U1-Southeast", 1.14,
  "Hardwick", "Worcester", "U1-Worcester", 1.08,
  "Harvard", "Worcester", "U1-Worcester", 1.08,
  "Harwich Port", "Barnstable", "Rec - East", 1.21,
  "Northwest Harwich", "Barnstable", "Rec - East", 1.21,
  "Harwich Center", "Barnstable", "Rec - East", 1.21,
  "East Harwich", "Barnstable", "Rec - East", 1.21,
  "Hatfield", "Hampshire", "U1-West", 1.10,
  "Haverhill", "Essex", "U1-Essex", 1.13,
  "Hawley", "Franklin", "R1", 1.17,
  "Heath", "Franklin", "R1", 1.17,
  "Hingham", "Plymouth", "U1-Boston", 1.07,
  "Hinsdale", "Berkshire", "R1", 1.17,
  "Holbrook", "Norfolk", "U1-Boston", 1.07,
  "Holden", "Worcester", "U1-Worcester", 1.08,
  "Holland", "Hampden", "U1-West", 1.10,
  "Holliston", "Middlesex", "U1-Boston", 1.07,
  "Holyoke", "Hampden", "U1-West", 1.10,
  "Hopedale", "Worcester", "U1-Worcester", 1.08,
  "Hopkinton", "Middlesex", "U1-Boston", 1.07,
  "Hubbardston", "Worcester", "U1-Worcester", 1.08,
  "Hudson", "Middlesex", "U1-Boston", 1.07,
  "Hull", "Plymouth", "U1-Boston", 1.07,
  "Huntington", "Hampshire", "U1-West", 1.10,
  "Ipswich", "Essex", "U1-Essex", 1.13,
  "Kingston", "Plymouth", "U1-Southeast", 1.14,
  "Lakeville", "Plymouth", "U1-Southeast", 1.14,
  "Lancaster", "Worcester", "U1-Worcester", 1.08,
  "South Lancaster", "Worcester", "U1-Worcester", 1.08,
  "Lanesborough", "Berkshire", "R1", 1.17,
  "Lawrence", "Essex", "U1-Essex", 1.13,
  "Lee", "Berkshire", "R1", 1.17,
  "Leicester", "Worcester", "U1-Worcester", 1.08,
  "Lenox Dale", "Berkshire", "R1", 1.17,
  "Leominster", "Worcester", "U1-Worcester", 1.08,
  "Leverett", "Franklin", "U1-West", 1.10,
  "Lexington", "Middlesex", "U1-Boston", 1.07,
  "Leyden", "Franklin", "R1", 1.17,
  "Lincoln", "Middlesex", "U1-Boston", 1.07,
  "Littleton Common", "Middlesex", "U1-Boston", 1.07,
  "Longmeadow", "Hampden", "U1-West", 1.10,
  "Lowell", "Middlesex", "U1-Boston", 1.07,
  "Ludlow", "Hampden", "U1-West", 1.10,
  "Lunenburg", "Worcester", "U1-Worcester", 1.08,
  "Lynn", "Essex", "U1-Essex", 1.13,
  "Lynnfield", "Essex", "U1-Essex", 1.13,
  "Malden", "Middlesex", "U1-Boston", 1.07,
  "Manchester-by-the-Sea", "Essex", "U1-Essex", 1.13,
  "Mansfield", "Bristol", "U1-Southeast", 1.14,
  "Mansfield Center", "Bristol", "U1-Southeast", 1.14,
  "Marblehead", "Essex", "U1-Essex", 1.13,
  "Marion Center", "Plymouth", "U1-Southeast", 1.14,
  "Marlborough", "Middlesex", "U1-Boston", 1.07,
  "Marshfield Hills", "Plymouth", "U1-Southeast", 1.14,
  "Mashpee Neck", "Barnstable", "Rec - East", 1.21,
  "Mattapoisett Center", "Plymouth", "U1-Southeast", 1.14,
  "Maynard", "Middlesex", "U1-Boston", 1.07,
  "Medfield", "Norfolk", "U1-Boston", 1.07,
  "Medford", "Middlesex", "U1-Boston", 1.07,
  "Medway", "Norfolk", "U1-Boston", 1.07,
  "Melrose", "Middlesex", "U1-Boston", 1.07,
  "Mendon", "Worcester", "U1-Worcester", 1.08,
  "Merrimac", "Essex", "U1-Essex", 1.13,
  "Methuen", "Essex", "U1-Essex", 1.13,
  "Middleborough Center", "Plymouth", "U1-Southeast", 1.14,
  "Middlefield", "Hampshire", "R1", 1.17,
  "Middleton", "Essex", "U1-Essex", 1.13,
  "Milford", "Worcester", "U1-Worcester", 1.08,
  "Millbury", "Worcester", "U1-Worcester", 1.08,
  "Millis", "Norfolk", "U1-Boston", 1.07,
  "Millis-Clicquot", "Norfolk", "U1-Boston", 1.07,
  "Millville", "Worcester", "U1-Worcester", 1.08,
  "Milton", "Norfolk", "U1-Boston", 1.07,
  "Monroe", "Franklin", "R1", 1.17,
  "Monson Center", "Hampden", "U1-West", 1.10,
  "Montague", "Franklin", "U1-West", 1.10,
  "Monterey", "Berkshire", "R1", 1.17,
  "Montgomery", "Hampden", "U1-West", 1.10,
  "Mount Washington", "Berkshire", "R1", 1.17,
  "Nahant", "Essex", "U1-Essex", 1.13,
  "Nantucket", "Nantucket", "Rec - Islands", 1.23,
  "Natick", "Middlesex", "U1-Boston", 1.07,
  "Needham", "Norfolk", "U1-Boston", 1.07,
  "New Ashford", "Berkshire", "R1", 1.17,
  "New Bedford", "Bristol", "U1-Southeast", 1.14,
  "New Braintree", "Worcester", "U1-Worcester", 1.08,
  "New Marlborough", "Berkshire", "R1", 1.17,
  "New Salem", "Franklin", "U1-West", 1.10,
  "Newbury", "Essex", "U1-Essex", 1.13,
  "Newburyport", "Essex", "U1-Essex", 1.13,
  "Newton", "Middlesex", "U1-Boston", 1.07,
  "Norfolk", "Norfolk", "U1-Boston", 1.07,
  "North Adams", "Berkshire", "R1", 1.17,
  "North Andover", "Essex", "U1-Essex", 1.13,
  "North Attleborough Town", "Bristol", "U1-Southeast", 1.14,
  "North Brookfield", "Worcester", "U1-Worcester", 1.08,
  "North Reading", "Middlesex", "U1-Boston", 1.07,
  "Northampton", "Hampshire", "U1-West", 1.10,
  "Northborough", "Worcester", "U1-Worcester", 1.08,
  "Northbridge", "Worcester", "U1-Worcester", 1.08,
  "Northfield", "Franklin", "R1", 1.17,
  "Norton", "Bristol", "U1-Southeast", 1.14,
  "Norton Center", "Bristol", "U1-Southeast", 1.14,
  "Norwell", "Plymouth", "U1-Southeast", 1.14,
  "Norwood", "Norfolk", "U1-Boston", 1.07,
  "Oak Bluffs", "Dukes", "Rec - Islands", 1.23,
  "Oakham", "Worcester", "U1-Worcester", 1.08,
  "Orange", "Franklin", "U1-West", 1.10,
  "Orleans", "Barnstable", "Rec - East", 1.21,
  "Otis", "Berkshire", "R1", 1.17,
  "Oxford", "Worcester", "U1-Worcester", 1.08,
  "Palmer Town", "Hampden", "U1-West", 1.10,
  "Paxton", "Worcester", "U1-Worcester", 1.08,
  "Peabody", "Essex", "U1-Essex", 1.13,
  "Pelham", "Hampshire", "U1-West", 1.10,
  "Pembroke", "Plymouth", "U1-Southeast", 1.14,
  "Pepperell", "Middlesex", "U1-Boston", 1.07,
  "East Pepperell", "Middlesex", "U1-Boston", 1.07,
  "Peru", "Berkshire", "R1", 1.17,
  "Petersham", "Worcester", "U1-Worcester", 1.08,
  "Phillipston", "Worcester", "U1-Worcester", 1.08,
  "Pittsfield", "Berkshire", "R1", 1.17,
  "Plainfield", "Hampshire", "R1", 1.17,
  "Plainville", "Norfolk", "U1-Southeast", 1.14,
  "Plymouth", "Plymouth", "U1-Southeast", 1.14,
  "North Plymouth", "Plymouth", "U1-Southeast", 1.14,
  "Plympton", "Plymouth", "U1-Southeast", 1.14,
  "Princeton", "Worcester", "U1-Worcester", 1.08,
  "Provincetown", "Barnstable", "Rec - East", 1.21,
  "Quincy", "Norfolk", "U1-Boston", 1.07,
  "Randolph Town", "Norfolk", "U1-Boston", 1.07,
  "Raynham Center", "Bristol", "U1-Southeast", 1.14,
  "Reading", "Middlesex", "U1-Boston", 1.07,
  "Rehoboth", "Bristol", "U1-Southeast", 1.14,
  "Revere", "Suffolk", "U1-Boston", 1.07,
  "Richmond", "Berkshire", "R1", 1.17,
  "Rochester", "Plymouth", "U1-Southeast", 1.14,
  "Rockland", "Plymouth", "U1-Southeast", 1.14,
  "Rockport", "Essex", "U1-Essex", 1.13,
  "Rowe", "Franklin", "R1", 1.17,
  "Rowley", "Essex", "U1-Essex", 1.13,
  "Royalston", "Worcester", "U1-Worcester", 1.08,
  "Russell", "Hampden", "U1-West", 1.10,
  "Rutland", "Worcester", "U1-Worcester", 1.08,
  "Salem", "Essex", "U1-Essex", 1.13,
  "Salisbury", "Essex", "U1-Essex", 1.13,
  "Sandisfield", "Berkshire", "R1", 1.17,
  "Sandwich", "Barnstable", "Rec - East", 1.21,
  "East Sandwich", "Barnstable", "Rec - East", 1.21,
  "Saugus", "Essex", "U1-Essex", 1.13,
  "Savoy", "Berkshire", "R1", 1.17,
  "Scituate", "Plymouth", "U1-Southeast", 1.14,
  "North Scituate", "Plymouth", "U1-Southeast", 1.14,
  "Seekonk", "Bristol", "U1-Southeast", 1.14,
  "North Seekonk", "Bristol", "U1-Southeast", 1.14,
  "Sharon", "Norfolk", "U1-Boston", 1.07,
  "Sheffield", "Berkshire", "R1", 1.17,
  "Shelburne", "Franklin", "R1", 1.17,
  "Sherborn", "Middlesex", "U1-Boston", 1.07,
  "Shirley", "Middlesex", "U1-Boston", 1.07,
  "Devens", "Middlesex", "U1-Boston", 1.09,
  "Shrewsbury", "Worcester", "U1-Worcester", 1.08,
  "Shutesbury", "Franklin", "U1-West", 1.10,
  "Somerset", "Bristol", "U1-Southeast", 1.14,
  "Somerville", "Middlesex", "U1-Boston", 1.07,
  "South Hadley", "Hampshire", "U1-West", 1.10,
  "Southampton", "Hampshire", "U1-West", 1.10,
  "Southborough", "Worcester", "U1-Worcester", 1.08,
  "Southbridge Town", "Worcester", "U1-Worcester", 1.08,
  "Southwick", "Hampden", "U1-West", 1.10,
  "Spencer", "Worcester", "U1-Worcester", 1.08,
  "Springfield", "Hampden", "U1-West", 1.10,
  "Sterling", "Worcester", "U1-Worcester", 1.08,
  "Stockbridge", "Berkshire", "R1", 1.17,
  "Stoneham", "Middlesex", "U1-Boston", 1.07,
  "Stoughton", "Norfolk", "U1-Boston", 1.07,
  "Stow", "Middlesex", "U1-Boston", 1.07,
  "Sturbridge", "Worcester", "U1-Worcester", 1.08,
  "Sudbury", "Middlesex", "U1-Boston", 1.07,
  "Sunderland", "Franklin", "U1-West", 1.10,
  "Sutton", "Worcester", "U1-Worcester", 1.08,
  "Swampscott", "Essex", "U1-Essex", 1.13,
  "Swansea", "Bristol", "U1-Southeast", 1.14,
  "Taunton", "Bristol", "U1-Southeast", 1.14,
  "Templeton", "Worcester", "U1-Worcester", 1.08,
  "Tewksbury", "Middlesex", "U1-Boston", 1.07,
  "Tisbury", "Dukes", "Rec - Islands", 1.23,
  "Tolland", "Hampden", "R1", 1.17,
  "Topsfield", "Essex", "U1-Essex", 1.13,
  "Townsend", "Middlesex", "U1-Boston", 1.07,
  "Truro", "Barnstable", "Rec - East", 1.21,
  "Tyngsborough", "Middlesex", "U1-Boston", 1.07,
  "Tyringham", "Berkshire", "R1", 1.17,
  "Upton", "Worcester", "U1-Worcester", 1.08,
  "Uxbridge", "Worcester", "U1-Worcester", 1.08,
  "Wakefield", "Middlesex", "U1-Boston", 1.07,
  "Wales", "Hampden", "U1-West", 1.10,
  "Walpole", "Norfolk", "U1-Boston", 1.07,
  "Waltham", "Middlesex", "U1-Boston", 1.07,
  "Ware", "Hampshire", "U1-West", 1.10,
  "Wareham Center", "Plymouth", "U1-Southeast", 1.14,
  "West Wareham", "Plymouth", "U1-Southeast", 1.14,
  "Warren", "Worcester", "U1-Worcester", 1.08,
  "West Warren", "Worcester", "U1-Worcester", 1.08,
  "Warwick", "Franklin", "R1", 1.17,
  "Washington", "Berkshire", "R1", 1.17,
  "Watertown", "Middlesex", "U1-Boston", 1.07,
  "Wayland", "Middlesex", "U1-Boston", 1.07,
  "Webster", "Worcester", "U1-Worcester", 1.08,
  "Wellesley", "Norfolk", "U1-Boston", 1.07,
  "Cochituate", "Norfolk", "U1-Boston", 1.07,
  "Wellfleet", "Barnstable", "Rec - East", 1.21,
  "Wendell", "Franklin", "U1-West", 1.10,
  "Wenham", "Essex", "U1-Essex", 1.13,
  "West Boylston", "Worcester", "U1-Worcester", 1.08,
  "West Bridgewater", "Plymouth", "U1-Southeast", 1.14,
  "West Brookfield", "Worcester", "U1-Worcester", 1.08,
  "West Newbury", "Essex", "U1-Essex", 1.13,
  "West Springfield", "Hampden", "U1-West", 1.10,
  "West Stockbridge", "Berkshire", "R1", 1.17,
  "West Tisbury", "Dukes", "Rec - Islands", 1.23,
  "Westborough", "Worcester", "U1-Worcester", 1.08,
  "Westfield", "Hampden", "U1-West", 1.10,
  "West Springfield Town", "Hampden", "U1-West", 1.10,
  "Westford", "Middlesex", "U1-Boston", 1.07,
  "Westhampton", "Hampshire", "U1-West", 1.10,
  "Westminster", "Worcester", "U1-Worcester", 1.08,
  "Weston", "Middlesex", "U1-Boston", 1.07,
  "Westport", "Bristol", "U1-Southeast", 1.14,
  "North Westport", "Bristol", "U1-Southeast", 1.14,
  "Westwood", "Norfolk", "U1-Boston", 1.07,
  "Weymouth Town", "Norfolk", "U1-Boston", 1.07,
  "Whately", "Franklin", "U1-West", 1.10,
  "Whitman", "Plymouth", "U1-Southeast", 1.14,
  "Wilbraham", "Hampden", "U1-West", 1.10,
  "Williamsburg", "Hampshire", "U1-West", 1.10,
  "Williamstown", "Berkshire", "R1", 1.17,
  "Wilmington", "Middlesex", "U1-Boston", 1.07,
  "Winchendon", "Worcester", "U1-Worcester", 1.08,
  "Winchester", "Middlesex", "U1-Boston", 1.07,
  "Windsor", "Berkshire", "R1", 1.17,
  "Winthrop Town", "Suffolk", "U1-Boston", 1.07,
  "Woburn", "Middlesex", "U1-Boston", 1.07,
  "Worcester", "Worcester", "U1-Worcester", 1.08,
  "Worthington", "Hampshire", "U1-West", 1.10,
  "Wrentham", "Norfolk", "U1-Boston", 1.07,
  "Yarmouth Port", "Barnstable", "Rec - East", 1.21,
  "West Yarmouth", "Barnstable", "Rec - East", 1.21,
  "South Yarmouth", "Barnstable", "Rec - East", 1.20,
  "East Douglas", "Worcester", "U1-Worcester", 1.08,
  "Whitinsville", "Worcester", "U1-Worcester", 1.08,
  "North Lakeville", "Plymouth", "U1-Southeast", 1.14,
  "North Pembroke", "Plymouth", "U1-Southeast", 1.14,
  "Monument Beach", "Barnstable", "Rec - East", 1.21,
  "Pocasset", "Barnstable", "Rec - East", 1.21,
  "Buzzards Bay", "Barnstable", "Rec - East", 1.19,
  "Onset", "Plymouth", "U1-Southeast", 1.16,
  "Sagamore", "Barnstable", "Rec - East", 1.20,
  "Smith Mills", "Bristol", "U1-Southeast", 1.14,
  "Bliss Corner", "Bristol", "U1-Southeast", 1.14,
  "Ocean Grove", "Bristol", "U1-Southeast", 1.12,
  "Marshfield", "Plymouth", "U1-Southeast", 1.14,
  "Cedar Crest", "Plymouth", "U1-Southeast", 1.14,
  "Green Harbor", "Plymouth", "U1-Southeast", 1.14,
  "Ocean Bluff-Brant Rock", "Plymouth", "U1-Southeast", 1.14,
)





options(tigris_use_cache = TRUE)

# Use cached boundaries
options(tigris_use_cache = TRUE)

# Load MA places shapefile
ma_places <- places(state = "MA", cb = TRUE, class = "sf")

# Match city names to boundaries
map_data <- ma_places %>%
  mutate(NAME = trimws(NAME)) %>%
  left_join(
    congestion_data %>% mutate(City = trimws(City)),
    by = c("NAME" = "City")
  )

# Define color palette based on congestion factor
pal <- colorNumeric("YlOrRd", domain = map_data$JAN_2024_Factor, na.color = "#808080")


htmltools::div(id = "map-container",
leaflet(map_data) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(
    fillColor = ~pal(JAN_2024_Factor),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.8,
      bringToFront = TRUE
    ),
    label = ~paste0(NAME, ": ", JAN_2024_Factor),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal,
    values = ~JAN_2024_Factor,
    opacity = 0.7,
    title = "Jan 2024 Congestion Factor",
    position = "bottomright"
  )
)
```


<style>
  #map-container {
    border: 2px solid black;
    box-shadow: 0 0 10px #333333;  /* Optional: subtle glow */
    padding: 4px;                  /* Adds space inside border */
    margin-bottom: 1em;
  }
</style>

